####  conda env create -f environment.yml


name: accentflow
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  # system libs
  - ffmpeg
  - libsndfile
  - numpy=1.22.*           # compatible with TTS 0.22.0 on py<=3.10
  - pandas=1.5.*
  # PyTorch + CUDA (uses your host NVIDIA driver)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1      # GPU-enabled build
  - pip:
      - streamlit==1.21.0
      - transformers==4.33.3
      - accelerate>=0.21.0,<1.0
      - sentencepiece>=0.1.99
      - nltk>=3.8
      - pydub==0.25.1
      - soundfile>=0.12
      - imageio-ffmpeg>=0.4.9
      - python-dotenv==0.21.1
      - TTS==0.22.0
      - diff-match-patch==20230430
      - edge-tts>=2.2.2,<8.0.0